name: northstark

channels:
  - conda-forge

dependencies:
  - python=3.12
  - openjdk=17
  - pandas
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
      - pyspark==4.1.1
      - plotly==6.7.0
      - pyarrow